### ISSUE TITLE
ntfy message formatting

### ISSUE THREAD

**Issue by x3nobyte** [lostkagamine/PushyFinder#12]
Hi.
I‘m using PushyFinder with ntfy, as the specific fork is not updated. Yesterday I recognized, that the formatting is off:
![IMG_1838](https://github.com/user-attachments/assets/94d6d5b6-7802-41e7-97d3-f6ae95b7686b)
Can you please check, whether you can implement the following code from the fork, instead of just forwarding the arguments:

        // Assuming `title` is used as the main message
        // Since ntfy doesn't have a separate title field, you can prepend it to the message or just send the message
        var message = string.IsNullOrEmpty(title) ? text : $"{title}: {text}";

Thanks in advance!

**Comment by lostkagamine** [comment]
Thank you for noticing. Would it be possible for you to open a pull request including the fixed code?

**Comment by lostkagamine** [comment]
You do not need to be a collaborator to publish code in a pull request - you make the commits against a fork of this repository (using the "Fork" button in the interface) then create a PR against here. Sorry, it's more complex but it keeps the source tree clean, plus you'll get official "contributor" status once it's accepted.

**Comment by lostkagamine** [comment]
Closed by #13
