### ISSUE TITLE
PushOver notifs coming up as (Encrypted)

### ISSUE THREAD

**Issue by GiacomoLaw** [lostkagamine/PushyFinder#2]
Lovely addon. Recently however the notifications are showing (Encrypted) rather than the message?

Thanks

**Comment by GiacomoLaw** [comment]
Seems to be an issue with the app itself.

**Comment by lostkagamine** [comment]
^ Huh, I'd never heard of this! Thank you for the report - what settings did you use to break it and then fix it?

**Comment by GiacomoLaw** [comment]
It just started to happen for me, then found this article: https://support.pushover.net/i58-notifications-showing-encrypted-on-iphone-ipad

Have restarted and will have to see if it shows up like that again. Apologies for the bogus issue and thanks for your work.
